name: Maven Package
on: [pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'temurin'
          cache: maven
      - name: Generate Java Client Library w/ the OpenAPITools Generator
        uses: openapi-generators/openapitools-generator-action@v1.5.0
        with:
          generator: java
          openapi-file: models/llamacpp.yml
          config-file: javasdk/openapi-generators-config.yml
          command-args: -o javasdk --global-property apiTests=false,modelTests=false
      - name: Package and run tests of Maven project for Java Client Library
        env:
          LLAMA_CPP_SERVER_HOSTNAME: ${{ secrets.LLAMA_CPP_SERVER_HOSTNAME }}
          LLAMA_CPP_COMPLETION_SERVER_PORT: ${{ secrets.LLAMA_CPP_COMPLETION_SERVER_PORT }}
          LLAMA_CPP_EMBEDDING_SERVER_PORT: ${{ secrets.LLAMA_CPP_EMBEDDING_SERVER_PORT }}
        run: |
          cd javasdk
          mvn -B package --no-transfer-progress --file pom.xml -Dmaven.test.skip
      - name: Publish to GitHub Packages Apache Maven
        run: mvn deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}