name: Maven Package
on: 
  pull_request:
    types: [closed]
jobs:
  publish-java-sdk:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'temurin'
          cache: maven
      - name: Generate Java Client Library w/ the OpenAPITools Generator
        uses: openapi-generators/openapitools-generator-action@v1.5.0
        with:
          generator: java
          openapi-file: models/llamacpp.yml
          config-file: javasdk/openapi-generators-config.yml
          command-args: -o javasdk --global-property apiTests=false,modelTests=false
      - name: Publish to GitHub Packages Apache Maven
        run: |
          cd javasdk
          mvn -B deploy --no-transfer-progress --file pom.xml -Dmaven.test.skip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}